apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    name: mydeployment
    type: front-end

spec:
  template:
    metadata:
      name: mypod
      labels:
        name: mypod
        env: test
        type: front-end

    spec:
      containers:
        - name: pod1
          image: nginx

  replicas: 3
  selector:
    matchlabels:
      type: front-end